/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the orderId service. Represents a row in the &quot;CrowdFunds_orderId&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.slayer.model.impl.orderIdModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.slayer.model.impl.orderIdImpl}.
 * </p>
 *
 * @author nithesh
 * @see orderId
 * @see com.slayer.model.impl.orderIdImpl
 * @see com.slayer.model.impl.orderIdModelImpl
 * @generated
 */
public interface orderIdModel extends BaseModel<orderId> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a order ID model instance should use the {@link orderId} interface instead.
	 */

	/**
	 * Returns the primary key of this order ID.
	 *
	 * @return the primary key of this order ID
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this order ID.
	 *
	 * @param primaryKey the primary key of this order ID
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the transaction ID of this order ID.
	 *
	 * @return the transaction ID of this order ID
	 */
	public long getTransactionId();

	/**
	 * Sets the transaction ID of this order ID.
	 *
	 * @param transactionId the transaction ID of this order ID
	 */
	public void setTransactionId(long transactionId);

	/**
	 * Returns the company ID of this order ID.
	 *
	 * @return the company ID of this order ID
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this order ID.
	 *
	 * @param companyId the company ID of this order ID
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the buyer of this order ID.
	 *
	 * @return the buyer of this order ID
	 */
	@AutoEscape
	public String getBuyer();

	/**
	 * Sets the buyer of this order ID.
	 *
	 * @param buyer the buyer of this order ID
	 */
	public void setBuyer(String buyer);

	/**
	 * Returns the create date of this order ID.
	 *
	 * @return the create date of this order ID
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this order ID.
	 *
	 * @param createDate the create date of this order ID
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the amount of this order ID.
	 *
	 * @return the amount of this order ID
	 */
	@AutoEscape
	public String getAmount();

	/**
	 * Sets the amount of this order ID.
	 *
	 * @param amount the amount of this order ID
	 */
	public void setAmount(String amount);

	/**
	 * Returns the currency type of this order ID.
	 *
	 * @return the currency type of this order ID
	 */
	@AutoEscape
	public String getCurrencyType();

	/**
	 * Sets the currency type of this order ID.
	 *
	 * @param currencyType the currency type of this order ID
	 */
	public void setCurrencyType(String currencyType);

	/**
	 * Returns the receiver email of this order ID.
	 *
	 * @return the receiver email of this order ID
	 */
	@AutoEscape
	public String getReceiverEmail();

	/**
	 * Sets the receiver email of this order ID.
	 *
	 * @param receiverEmail the receiver email of this order ID
	 */
	public void setReceiverEmail(String receiverEmail);

	/**
	 * Returns the payer email of this order ID.
	 *
	 * @return the payer email of this order ID
	 */
	@AutoEscape
	public String getPayerEmail();

	/**
	 * Sets the payer email of this order ID.
	 *
	 * @param payerEmail the payer email of this order ID
	 */
	public void setPayerEmail(String payerEmail);

	/**
	 * Returns the debit of this order ID.
	 *
	 * @return the debit of this order ID
	 */
	@AutoEscape
	public String getDebit();

	/**
	 * Sets the debit of this order ID.
	 *
	 * @param debit the debit of this order ID
	 */
	public void setDebit(String debit);

	/**
	 * Returns the credit of this order ID.
	 *
	 * @return the credit of this order ID
	 */
	@AutoEscape
	public String getCredit();

	/**
	 * Sets the credit of this order ID.
	 *
	 * @param credit the credit of this order ID
	 */
	public void setCredit(String credit);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(orderId orderId);

	@Override
	public int hashCode();

	@Override
	public CacheModel<orderId> toCacheModel();

	@Override
	public orderId toEscapedModel();

	@Override
	public orderId toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}